"""Добавлена модель AccreditationApplication

Revision ID: 251650141924
Revises: d6303ae0fe0f
Create Date: 2025-04-15 20:03:11.269487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251650141924'
down_revision = 'd6303ae0fe0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.alter_column('inviter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('invitee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.alter_column('invitee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('inviter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
