"""Добавлена модель EventInvitation с relationship event

Revision ID: 3a07fccfe03a
Revises: efc09199b6d3
Create Date: 2025-04-14 19:31:28.810999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a07fccfe03a'
down_revision = 'efc09199b6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitations') as batch_op:
        batch_op.add_column(sa.Column('inviter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invitee_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('event_invitations_inviter_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('event_invitations_invitee_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], ondelete='CASCADE')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitee_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('inviter_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_invitations_invitee_id_fkey', 'users', ['invitee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('event_invitations_inviter_id_fkey', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
