"""Добавлено поле events_public в модель User

Revision ID: 8df989582fa8
Revises: d0e2f5bda57e
Create Date: 2025-04-13 18:35:12.442124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df989582fa8'
down_revision = 'd0e2f5bda57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events_public', sa.Boolean(), nullable=True))
        batch_op.drop_column('attended_events_public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attended_events_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('events_public')

    # ### end Alembic commands ###
