"""Добавлены поля для хранения исходных имён файлов в AccreditationApplication

Revision ID: bde7ce484156
Revises: d86669c13497
Create Date: 2025-04-15 22:47:42.126544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde7ce484156'
down_revision = 'd86669c13497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accreditation_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_copy_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('individual_registration_doc_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('egrul_extract_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tax_certificate_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('license_doc_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('professional_experience_docs_filename', sa.String(length=255), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('registration_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('organization_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('legal_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('actual_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('ceo_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)


    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('accreditation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accreditation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.alter_column('invitee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('inviter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('accreditation_applications', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('ceo_name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('actual_address',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('legal_address',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('organization_name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('registration_address',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('professional_experience_docs_filename')
        batch_op.drop_column('license_doc_filename')
        batch_op.drop_column('tax_certificate_filename')
        batch_op.drop_column('egrul_extract_filename')
        batch_op.drop_column('individual_registration_doc_filename')
        batch_op.drop_column('passport_copy_filename')

    # ### end Alembic commands ###
