"""Добавлено поле attended_events_public в модель User

Revision ID: d0e2f5bda57e
Revises: 
Create Date: 2025-04-13 18:11:10.783788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e2f5bda57e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_images')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('events_organizer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['organizer_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attended_events_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('attended_events_public')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('events_organizer_id_fkey', 'users', ['organizer_id'], ['id'], ondelete='CASCADE')

    op.create_table('event_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_images_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_images_pkey')
    )
    # ### end Alembic commands ###
