"""Добавлен статус аккредитации в таблицу users

Revision ID: d6303ae0fe0f
Revises: 3a07fccfe03a
Create Date: 2025-04-15 19:53:34.755479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6303ae0fe0f'
down_revision = '3a07fccfe03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inviter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invitee_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('event_invitations_recipient_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('event_invitations_sender_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['invitee_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accreditation_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('accreditation_rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('accreditation_rejection_reason')
        batch_op.drop_column('accreditation_status')

    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inviter_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invitee_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_invitations_sender_id_fkey', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('event_invitations_recipient_id_fkey', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
