"""Увеличена длина текстовых полей в модели AccreditationApplication

Revision ID: d86669c13497
Revises: 251650141924
Create Date: 2025-04-15 20:19:08.780681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86669c13497'
down_revision = '251650141924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accreditation_applications', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('registration_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('organization_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('legal_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('actual_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('ceo_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('passport_copy',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               postgresql_using="CASE WHEN passport_copy IS NULL OR passport_copy = '' THEN NULL ELSE passport_copy::bytea END")
        batch_op.alter_column('individual_registration_doc',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('egrul_extract',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('tax_certificate',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('license_doc',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('professional_experience_docs',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.alter_column('inviter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('invitee_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.alter_column('invitee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('inviter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('accreditation_applications', schema=None) as batch_op:
        batch_op.alter_column('professional_experience_docs',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('license_doc',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('tax_certificate',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('egrul_extract',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('individual_registration_doc',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('passport_copy',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('ceo_name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('actual_address',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('legal_address',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('organization_name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('registration_address',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
